# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Sentence')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('query_body', models.TextField(verbose_name='Query Body')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
