# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='url',
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(blank=True, help_text='https://twitter.com/efeoge/status/748450479600959488 için 748450479600959488', max_length=255, verbose_name='Id of Tweet'),
        ),
    ]
