# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20161227_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweet', to='sentences.Sentence'),
        ),
    ]
